### ISSUE TITLE
可以给出，user，t_leave 表数据结构及初始数据吗

### ISSUE THREAD

**Issue by ZWShuai91** [Anthony-Lu/activiti-test-lxb#2]

**Comment by Pickerer** [comment]
表数据可以给我一份么

**Comment by jackychan123** [comment]
数据表可以给我一份吗?

**Comment by liaoxuewei** [comment]
同问

**Comment by liaoxuewei** [comment]
CREATE TABLE `t_leave` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `leave_date` datetime DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `content` varchar(1000) DEFAULT NULL,
  `state` int(11) DEFAULT NULL,
  `remark` varchar(100) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `role` varchar(100) DEFAULT NULL,
  `manager_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
本想自己动手丰衣足食，创建了表，竟然还不行，这~~~

**Comment by liaoxuewei** [comment]
修正：
CREATE TABLE `t_leave` (
  `id` varchar(100) NOT NULL,
  `leave_date` datetime DEFAULT NULL,
  `days` int(11) DEFAULT NULL,
  `content` varchar(1000) DEFAULT NULL,
  `state` int(11) DEFAULT NULL,
  `remark` varchar(100) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `role` varchar(100) DEFAULT NULL,
  `manager_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
insert into user(name) values('范冰冰');

**Comment by liaoxuewei** [comment]
入口：
localhost:8080/user/toLogin
但是依然还是有不少问题。。。

**Comment by liaoxuewei** [comment]
为什么关闭呢，都还没有解决全部问题呢
